In [1]:
import numpy as np

def fib(n):
    if n == 0:
        return 0 # vraci 0, nulty clen se rovna 0
    elif n == 1 or n == 2: 
        return 1 # vraci 1, protoze 1. a 2. clen Fibonacciho posloupnosti se rovna 1
    elif n < 0:
        return None # pouze pro pripad nefunkci matice -> spatne vypisuje, chyba v zadani
    else:
        return fib(n-1) + fib(n-2) # rekurzivni reseni fibonacciho posloupnosti

# def matrix(n):
#     mat = np.zeros((5,5),dtype=int) # vytvori prazdnou matici
#     for i in range(n):
#         for j in range(n):
#             mat[i][j] = fib((3*(i+1)-2*(j+1))) # a[i,j]=F(3i-2j)

#     mat[2][4] = 0 # prepocitejte prvek a[3,5]=0
#     for j in range(n):
#         mat[2][j] = 3*mat[1][j]-2*mat[0][j]  # prepocitejte prvky ve tretim radku a[3,j]=3a[2,j]-2a[1,j]
#     return mat # vraci hotovou matici, nelze pouzit kvuli chybnemu zadani

In [3]:
def gaussian_elimination(A, b):
    n = len(A) # velikost matice (5x5), tedy n=5
    # pivot je prvni nenulovy prvek v kazdem radku
    # nalevo od pivotu a pod nim se snazime v matici mit jen nuly
    for i in range(n):
        max_pivot = abs(A[i][i]) # hledame hodnotu pivotu v matici -> nejvyssi cislo bude po uprave matice[0][0]
        max_row = i # radek matice s pivotem
        for k in range(i + 1, n): # projde cisla pod pivotem
            if abs(A[k][i]) > max_pivot: # pokud je cislo pod pivotem vyssi nez pivot, tak se hodnota prepise
                max_pivot = abs(A[k][i]) # odkaz na pravidla s praci s pivotem ->
                max_row = k              # -> https://people.richland.edu/james/lecture/m116/matrices/pivot.html

        # vymenime radek s kterym pracujeme s radkem kde je momentalne pivot
        if max_row != i:
            A[i], A[max_row] = A[max_row], A[i] # vymeni radky v matici
            b[i], b[max_row] = b[max_row], b[i] # vymeni radky ve vektoru

        # nulujeme cisla pod pivotem v matici
        for k in range(i + 1, n): # (i+1) -> pracujeme s radkem pod pivotem
            c = -A[k][i] / A[i][i] # cislo ktere upravuje dalsi hodnoty v matici
            for j in range(i, n):
                A[k][j] += c * A[i][j] # vynuluje cisla pod pivotem, dalsi hodnoty upravi
            b[k] += c * b[i] # u vektoru cislo upravujeme take

    print(f"Matice po uprave: \n{np.asarray(A)}")
    print(f"Vektor po uprave: \n{b}")

    # zpetna substituce 
    x = [0 for i in range(n)] # pripravi se 5 nulovych hodnot
    for i in range(n - 1, -1, -1): # prochazi radky zespod matice
        x[i] = b[i] # nejdriv zapise hodnotu z upraveneho vektoru
        for k in range(i + 1, n):
            x[i] -= A[i][k] * x[k] # odstrani prebytecne promenne -> prevede na druhou stranu rovnice
        x[i] /= A[i][i] # vypocet dane promenne, tedy x5,x4,x3,x2,x1...


    return x

In [4]:
A = [[1, 5, 13, 34, 89],[3, 1, 0, 8, 21],[7, -7, -26, -44, 0],[55, 21, 8, 3, 1],[233, 89, 34, 13, 5]] #matice A
b = [fib(0), fib(1), fib(2), fib(3), fib(4)] #vektor b

print(f"Puvodni matice: \n{np.asarray(A)}")
print(f"Puvodni vektor: \n{b}")
print(f"Numericke reseni: {gaussian_elimination(A,b)}") #numericke reseni gaussovy eliminace matice a vektoru
print(f"Analyticke reseni: {np.linalg.solve(np.asarray(A, dtype=float), np.asarray(b, dtype=float))}") #analyticke reseni pomoci knihovny numpy

Puvodni matice: 
[[  1   5  13  34  89]
 [  3   1   0   8  21]
 [  7  -7 -26 -44   0]
 [ 55  21   8   3   1]
 [233  89  34  13   5]]
Puvodni vektor: 
[0, 1, 1, 2, 3]
Matice po uprave: 
[[ 2.33000000e+02  8.90000000e+01  3.40000000e+01  1.30000000e+01
   5.00000000e+00]
 [ 0.00000000e+00 -9.67381974e+00 -2.70214592e+01 -4.43905579e+01
  -1.50214592e-01]
 [ 0.00000000e+00  0.00000000e+00 -4.52528838e-02  1.27533274e+01
   8.89068323e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.29411765e-01
  -3.66666667e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.46944695e-18  0.00000000e+00
  -3.83333333e+01]]
Vektor po uprave: 
[3, 0.9098712446351931, 0.42147293700088734, 1.2745098039215381, 0.6666666666669093]
Numericke reseni: [-637.4999999988697, 1932.1608695617915, -687.9999999987806, -2.286956521734775, -0.017391304347832422]
Analyticke reseni: [-6.37500000e+02  1.93216087e+03 -6.88000000e+02 -2.28695652e+00
 -1.73913043e-02]
